import numpy;

let data := [2, 3];
let result := zeros(data);

println(result);

let input := [1, 2, 3, 4];
let s := sum(input);
println(s);

let first := [1, 2, 3, 4];
let second := [1, 2, 3, 4];
let d := dot(first, second);
println(d);

let array_to_reshape := [1, 2, 3, 4];
let shape := [2, 2];
let reshaped_array := reshape(array_to_reshape, shape);
println(reshaped_array);

let added := add(first, second);
println(added);